<a href="https://colab.research.google.com/github/ravikrishnareddy/deep_learning/blob/main/ZeroToMastery/00_tensorflow_fundamentals_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [4]:
# Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

s = tf.constant(3)
print('scalar: ', s)
print(type(s))
print(s.ndim)
print('')

v = tf.constant([7, 10])
print('vector: ', v)
print(type(v))
print(v.ndim)
print('')

m = tf.constant([[2, 3], 
                 [7, 10]])
print('matrix: ', m)
print(type(m))
print(m.ndim)
print('')

t = tf.constant([[[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]]])
print('tensor: ', t)
print(type(t))
print(t.ndim)
print('')

scalar:  tf.Tensor(3, shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
0

vector:  tf.Tensor([ 7 10], shape=(2,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
1

matrix:  tf.Tensor(
[[ 2  3]
 [ 7 10]], shape=(2, 2), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
2

tensor:  tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(1, 3, 3), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
3



In [10]:
# Find the shape, rank and size of the tensors you created in 1
print('shape: ', t.shape)
print('rank: ', tf.rank(t).numpy())
print('size: ', tf.size(t).numpy())

shape:  (1, 3, 3)
rank:  3
size:  9


In [16]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300]
tensor_1 = tf.constant(tf.random.stateless_uniform(shape=[5, 300], seed=(0, 1), minval=0, maxval=1))
print(tensor_1)
print('')
tensor_2 = tf.constant(tf.random.stateless_uniform(shape=[5, 300], seed=(0, 2), minval=0, maxval=1))
print(tensor_2)

tf.Tensor(
[[0.08216608 0.40928006 0.39318466 ... 0.39660907 0.4784795  0.91761565]
 [0.01828551 0.44946778 0.92918336 ... 0.6696019  0.86210024 0.8076656 ]
 [0.4117663  0.770141   0.33105493 ... 0.6711476  0.85589325 0.93851113]
 [0.21303272 0.44056177 0.7896323  ... 0.8288938  0.21916342 0.956254  ]
 [0.9305494  0.5015509  0.8514749  ... 0.02131653 0.5989225  0.5082902 ]], shape=(5, 300), dtype=float32)

tf.Tensor(
[[0.38320196 0.6836976  0.84488106 ... 0.93043756 0.1856631  0.57123184]
 [0.27986813 0.78495836 0.8809737  ... 0.80925286 0.44890392 0.6020223 ]
 [0.3728615  0.8101733  0.7210413  ... 0.30136347 0.5237329  0.5810863 ]
 [0.8001467  0.41929376 0.5334585  ... 0.7891644  0.17133951 0.7901368 ]
 [0.61018944 0.36475742 0.94783676 ... 0.45684135 0.37415504 0.6884068 ]], shape=(5, 300), dtype=float32)


In [18]:
# Multiply the two tensors you created in 3 using matrix multiplication.
tensor_1_2_matmul = tf.matmul(tensor_1, tf.transpose(tensor_2))
print(tensor_1_2_matmul)

tf.Tensor(
[[73.960434 80.24075  79.02925  76.175735 75.76964 ]
 [72.01323  77.32151  77.78919  70.23007  75.89364 ]
 [76.39591  79.785065 76.76315  75.97728  75.999176]
 [73.707405 79.501724 78.87918  73.24406  78.50473 ]
 [77.59998  81.472786 81.44474  76.17197  80.63745 ]], shape=(5, 5), dtype=float32)


In [21]:
# Multiply the two tensors you created in 3 using dot product.
tensor_1_2_dot = tf.tensordot(tensor_1, tf.transpose(tensor_2), axes=1)
print(tensor_1_2_dot)

tf.Tensor(
[[73.960434 80.24075  79.02925  76.175735 75.76964 ]
 [72.01323  77.32151  77.78919  70.23007  75.89364 ]
 [76.39591  79.785065 76.76315  75.97728  75.999176]
 [73.707405 79.501724 78.87918  73.24406  78.50473 ]
 [77.59998  81.472786 81.44474  76.17197  80.63745 ]], shape=(5, 5), dtype=float32)


In [22]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor_3 = tf.random.stateless_uniform(shape=[224, 224, 3], seed=(0, 1), minval=0, maxval=1)
print(tensor_3)

tf.Tensor(
[[[0.08216608 0.40928006 0.39318466]
  [0.3162533  0.34717774 0.73199546]
  [0.56369007 0.9769211  0.55243933]
  ...
  [0.9238517  0.74884343 0.27838945]
  [0.79498756 0.44773757 0.5954931 ]
  [0.774982   0.18768477 0.36871493]]

 [[0.39124548 0.52653253 0.98199475]
  [0.9022242  0.98764503 0.86433923]
  [0.19658887 0.7567464  0.34634674]
  ...
  [0.5774715  0.791064   0.853372  ]
  [0.9585072  0.24212122 0.4072547 ]
  [0.896675   0.48084855 0.16755211]]

 [[0.08823133 0.02116656 0.4411217 ]
  [0.5371903  0.6499002  0.96041346]
  [0.28728902 0.3055538  0.02413893]
  ...
  [0.5683601  0.6161053  0.15821028]
  [0.6293392  0.66284    0.677814  ]
  [0.5619303  0.65048957 0.11560786]]

 ...

 [[0.17193723 0.16156793 0.53142476]
  [0.0595243  0.7454133  0.89403033]
  [0.57041407 0.45257127 0.46690834]
  ...
  [0.08229828 0.38555872 0.5923791 ]
  [0.07422912 0.6231595  0.93623257]
  [0.58755994 0.9076154  0.9154035 ]]

 [[0.14526987 0.59365416 0.33990538]
  [0.7642752  0.86882246 0

In [28]:
# Find the min and max values of the tensor you created in 6 along the first axis.
print('Min:', tf.reduce_min(tensor_3[:,0,0]).numpy())
print('Max:', tf.reduce_max(tensor_3[:,0,0]).numpy())

Min: 0.0019071102
Max: 0.998603


In [30]:
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor_4 = tf.random.uniform(shape=[1, 224, 224, 3])
tensor_4_squeezed = tf.squeeze(tensor_4, axis=0)
print(tensor_4_squeezed.shape)

(224, 224, 3)


In [3]:
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor_5 = tf.random.uniform(shape=[10])
print('Tensor Data: ', tensor_5.numpy())
print('')
print('Index with max value: ', tf.argmax(tensor_5).numpy())
print('')
print('Max value: ', tensor_5[tf.argmax(tensor_5)].numpy())

Tensor Data:  [0.74159765 0.4844247  0.9006101  0.17725158 0.8760228  0.804616
 0.37453854 0.14813292 0.96616805 0.28262496]

Index with max value:  8

Max value:  0.96616805


In [8]:
# One-hot encode the tensor you created in 9.
print(tensor_5.numpy())
print('')
tf.one_hot(tf.cast(tensor_5, dtype=tf.int32), depth=10)

[0.74159765 0.4844247  0.9006101  0.17725158 0.8760228  0.804616
 0.37453854 0.14813292 0.96616805 0.28262496]



<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [14]:
# Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
# How would you calculate your grocery bill for the month and for the year using tensors?
tensor_grocery_bill = tf.constant([[2201, 45], 
                                   [2202, 83], 
                                   [2203, 74], 
                                   [2204, 47], 
                                   [2205, 23], 
                                   [2206, 30], 
                                   [2207, 43]])
print(tensor_grocery_bill.numpy())
print('')
recent_month_year_position = tf.argmax(tensor_grocery_bill[:,0])
print('Most recent grocery bill: ', tensor_grocery_bill[:,1][recent_month_year_position].numpy())

[[2201   45]
 [2202   83]
 [2203   74]
 [2204   47]
 [2205   23]
 [2206   30]
 [2207   43]]

Most recent grocery bill:  43
