<a href="https://colab.research.google.com/github/ravikrishnareddy/deep_learning/blob/main/ZeroToMastery/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.8.2


In [ ]:
scalar = tf.constant(7)
print(scalar)
print(type(scalar))
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
0


In [ ]:
vector = tf.constant([1,2,3])
print(vector)
print(type(vector))
print(vector.ndim)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
1


In [ ]:
matrix = tf.constant([[1,2,3],[4,5,6]])
print(matrix)
print(type(matrix))
print(matrix.ndim)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
2


In [ ]:
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)
print(type(tensor))
print(tensor.ndim)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
3


In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# note that tf.constant is immutable
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

In [ ]:
random_tensor_1 = tf.random.Generator.from_seed(42)
random_tensor_1 = random_tensor_1.normal(shape=(3,2))

random_tensor_2 = tf.random.Generator.from_seed(42)
random_tensor_2 = random_tensor_2.normal(shape=(3,2))

In [ ]:
print(random_tensor_1)
print(random_tensor_2)
random_tensor_1 == random_tensor_2

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [ ]:
unchangeable_tensor = tf.constant([[1,2,3],
                                   [4,5,6],
                                   [7,8,9]])

tf.random.shuffle(unchangeable_tensor)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
tf.random.set_seed(24)
tf.random.shuffle(unchangeable_tensor)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]], dtype=int32)>

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3,4,5,6])
a2 = np.array([1,2,3,4,5,6,7,8,9])

print(a1)
print(a2)

[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8 9]


In [ ]:
tf.constant(a1)

<tf.Tensor: shape=(6,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6])>

In [ ]:
tf.constant(a2, shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [ ]:
tf.Variable(a2, shape=(3,3))

ValueError: ignored

In [ ]:
tf.Variable(a2.reshape(3,3))

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [ ]:
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(7,7))

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [4]:
# create rank 2 tensor
tf_rank_two = tf.constant([[10, 7], 
                           [4, 3]])
print(tf_rank_two)
print(tf_rank_two.ndim)

tf.Tensor(
[[10  7]
 [ 4  3]], shape=(2, 2), dtype=int32)
2


In [5]:
tf_rank_two[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>

In [7]:
# Add new axis to the rank 2 tensor to add one more dimension
tf_rank_three = tf_rank_two[..., tf.newaxis]
print(tf_rank_three)
tf_rank_three.ndim

tf.Tensor(
[[[10]
  [ 7]]

 [[ 4]
  [ 3]]], shape=(2, 2, 1), dtype=int32)


3

In [8]:
# Expand dimensions is an alternative for tf.newaxis
tf.expand_dims(tf_rank_two, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 4],
        [ 3]]], dtype=int32)>

In [9]:
tf.expand_dims(tf_rank_two, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 4,  3]]], dtype=int32)>

In [10]:
tf.expand_dims(tf_rank_two, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 4,  3]]], dtype=int32)>

In [13]:
# Basic operations

tensor = tf.constant([[10, 7], [3, 4]])
print(tensor)

# Addition
print(tensor + 10)

# Subtraction
print(tensor -2)

# Multiply
print(tensor * 2)

# Division
print(tensor / 2)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[8 5]
 [1 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 14]
 [ 6  8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5.  3.5]
 [1.5 2. ]], shape=(2, 2), dtype=float64)


In [17]:
tensor = tf.constant([[10, 7], [3, 4]])

print(tensor)

print(tf.add(tensor, 10))

print(tf.subtract(tensor, 10))

print(tf.multiply(tensor, 10))

print(tf.divide(tensor, 10))

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  0.7]
 [0.3 0.4]], shape=(2, 2), dtype=float64)
