<a href="https://colab.research.google.com/github/ravikrishnareddy/deep_learning/blob/main/ZeroToMastery/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

In [ ]:
print(tf.__version__)

2.8.2


In [ ]:
scalar = tf.constant(7)
print(scalar)
print(type(scalar))
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
0


In [ ]:
vector = tf.constant([1,2,3])
print(vector)
print(type(vector))
print(vector.ndim)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
1


In [ ]:
matrix = tf.constant([[1,2,3],[4,5,6]])
print(matrix)
print(type(matrix))
print(matrix.ndim)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
2


In [ ]:
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)
print(type(tensor))
print(tensor.ndim)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
3


In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# note that tf.constant is immutable
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

In [ ]:
random_tensor_1 = tf.random.Generator.from_seed(42)
random_tensor_1 = random_tensor_1.normal(shape=(3,2))

random_tensor_2 = tf.random.Generator.from_seed(42)
random_tensor_2 = random_tensor_2.normal(shape=(3,2))

In [ ]:
print(random_tensor_1)
print(random_tensor_2)
random_tensor_1 == random_tensor_2

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [ ]:
unchangeable_tensor = tf.constant([[1,2,3],
                                   [4,5,6],
                                   [7,8,9]])

tf.random.shuffle(unchangeable_tensor)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]], dtype=int32)>

In [ ]:
tf.random.set_seed(24)
tf.random.shuffle(unchangeable_tensor)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]], dtype=int32)>

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3,4,5,6])
a2 = np.array([1,2,3,4,5,6,7,8,9])

print(a1)
print(a2)

[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8 9]


In [ ]:
tf.constant(a1)

<tf.Tensor: shape=(6,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6])>

In [ ]:
tf.constant(a2, shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [ ]:
tf.Variable(a2, shape=(3,3))

ValueError: ignored

In [ ]:
tf.Variable(a2.reshape(3,3))

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [ ]:
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(7,7))

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# create rank 2 tensor
tf_rank_two = tf.constant([[10, 7], 
                           [4, 3]])
print(tf_rank_two)
print(tf_rank_two.ndim)

tf.Tensor(
[[10  7]
 [ 4  3]], shape=(2, 2), dtype=int32)
2


In [ ]:
tf_rank_two[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>

In [ ]:
# Add new axis to the rank 2 tensor to add one more dimension
tf_rank_three = tf_rank_two[..., tf.newaxis]
print(tf_rank_three)
tf_rank_three.ndim

tf.Tensor(
[[[10]
  [ 7]]

 [[ 4]
  [ 3]]], shape=(2, 2, 1), dtype=int32)


3

In [ ]:
# Expand dimensions is an alternative for tf.newaxis
tf.expand_dims(tf_rank_two, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 4],
        [ 3]]], dtype=int32)>

In [ ]:
tf.expand_dims(tf_rank_two, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 4,  3]]], dtype=int32)>

In [ ]:
tf.expand_dims(tf_rank_two, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 4,  3]]], dtype=int32)>

In [ ]:
# Basic operations

tensor = tf.constant([[10, 7], [3, 4]])
print(tensor)

# Addition
print(tensor + 10)

# Subtraction
print(tensor -2)

# Multiply
print(tensor * 2)

# Division
print(tensor / 2)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[8 5]
 [1 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 14]
 [ 6  8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5.  3.5]
 [1.5 2. ]], shape=(2, 2), dtype=float64)


In [ ]:
tensor = tf.constant([[10, 7], [3, 4]])

print(tensor)

print(tf.add(tensor, 10))

print(tf.subtract(tensor, 10))

print(tf.multiply(tensor, 10))

print(tf.divide(tensor, 10))

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  0.7]
 [0.3 0.4]], shape=(2, 2), dtype=float64)


In [ ]:
# Matrix Multiplication
matrix_1 = tf.constant([[1, 2, 3], [4, 5, 6]])
matrix_2 = tf.constant([1, 2, 1], shape=(3, 1))

print(matrix_1)

print(matrix_2)

tf.matmul(matrix_1, matrix_2)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [1]], shape=(3, 1), dtype=int32)


<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 8],
       [20]], dtype=int32)>

In [ ]:
# Operator @ can be used for matrix multiplication instead of matmul

matrix_1 @ matrix_2

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 8],
       [20]], dtype=int32)>

In [ ]:
tensor_1 = tf.constant([[1, 2, 5], 
                        [7, 2, 1], 
                        [3, 3, 3]])
print(tensor_1)

print('')

tensor_2 = tf.constant([[3, 5], 
                        [6, 7], 
                        [1, 8]])
print(tensor_2)

print('')

tensor_1 @ tensor_2

tf.Tensor(
[[1 2 5]
 [7 2 1]
 [3 3 3]], shape=(3, 3), dtype=int32)

tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
X = tf.constant([[1, 2], 
                 [3, 4], 
                 [5, 6]])
print(X.shape)

print('')

Y = tf.constant([[7, 8], 
                 [9, 10], 
                 [11, 12]])
print(Y.shape)

print('')

X @ Y

(3, 2)

(3, 2)



InvalidArgumentError: ignored

In [ ]:
# Note that above operation failed due to incompatible shapes between two tensors

tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# In addition to matmul and @, we have tenforflow function tensordot() to perform matrix multiplication

X = tf.constant([[1, 2], 
                 [3, 4]])
print(X)

print('')

Y = tf.constant([[1, 1], 
                 [2, 2]])
print(Y)

print('')

tf.tensordot(X, Y, axes=1)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[1 1]
 [2 2]], shape=(2, 2), dtype=int32)



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  5],
       [11, 11]], dtype=int32)>

In [ ]:
# Chaning datatype pricision from 32-bit to 16-bit using tensorflow's cast function

print(X)

print(tf.cast(X, dtype=tf.int16))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int16)


In [ ]:
# Converting numbers to absolute numbers

A = tf.constant([-7, -10])
print(A)

print('')

tf.abs(A)

tf.Tensor([ -7 -10], shape=(2,), dtype=int32)



<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# Get the minimum number from a tensor

M = tf.constant(np.random.randint(0, 100, size=50))
print(M)

print('')

tf.reduce_min(M)

tf.Tensor(
[ 9 53 47 51 59 11 38 44 11 50 27 50 52  1 98 70 54 27 51 25 20 57 81 30
 31 87 63  3  2 53 68 30 99 49 30 53 36 49 42 28 13 58 26 77 19 83 88 80
 66 68], shape=(50,), dtype=int64)



<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# Get the maximum number from a tensor
tf.reduce_max(M)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# Get the mean of a tensor
tf.reduce_mean(M)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [ ]:
# Get the sum of a tensor
S = tf.reduce_sum(M)
S.numpy()

2317

In [ ]:
# Get the variance of a tensor
tf.math.reduce_variance(tf.cast(M, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=637.0>

In [ ]:
# Get the standard deviatin of a tensor
tf.math.reduce_std(tf.cast(M, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=25.23>

In [ ]:
# Another way for variance calculation
tfp.stats.variance(M)

<tf.Tensor: shape=(), dtype=int64, numpy=637>

In [ ]:
# Another way for standard deviation calculation
tfp.stats.stddev(tf.cast(M, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=25.24489>

In [ ]:
# Get maximum position
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Do indexing to get max value using position of the max value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the positional minimum
print(tf.argmin(F))

print('')

print(F[tf.argmin(F)])

tf.Tensor(16, shape=(), dtype=int64)

tf.Tensor(0.009463668, shape=(), dtype=float32)


In [ ]:
# Squeezing a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [12]:
# Create one hot encoding using tensorflow
colors = tf.constant(['Red', 'Green', 'Blue'])
print(colors)

print('')

tf.cast(colors, dtype=tf.float32)

tf.Tensor([b'Red' b'Green' b'Blue'], shape=(3,), dtype=string)



UnimplementedError: ignored