In [1]:
import numpy as np

In [2]:
a1 = np.array([
    [[1,2,3],
     [4,5,6],
     [7,8,9]],
    [[10,11,12],
     [13,14,15],
     [16,17,18]]
])

In [3]:
a1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(2, 3, 3)

In [12]:
a2 = np.array([
    [1,2,3],
    [4,5,6]
])

In [13]:
a2.shape

(2, 3)

In [14]:
a1.ndim

3

In [15]:
a2.ndim

2

In [17]:
# Check the performance speed of a python and numpy functions
numpy_array = np.random.random(100000)

%timeit sum(numpy_array)
%timeit np.sum(numpy_array)

26.2 ms ± 2.89 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
147 µs ± 13.2 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [18]:
26200 / 147

178.2312925170068

In [20]:
print(np.std(numpy_array))
print(np.sqrt(np.var(numpy_array)))

0.2886567325586009
0.2886567325586009


In [25]:
butter_sales = np.random.randint(20, size=(5,3))
butter_prices = np.random.randint(12, size=(3,1))

print(butter_sales,end='\n\n')
print(butter_prices)

[[13  8 17]
 [ 7 11 10]
 [10  7 18]
 [19  1  5]
 [16 19  5]]

[[11]
 [ 9]
 [ 0]]


In [27]:
np.dot(butter_sales, butter_prices)

array([[215],
       [176],
       [173],
       [218],
       [347]])